# Generated by Django 4.2.1 on 2023-06-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="daily_target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("amt", models.CharField(max_length=10)),
                ("amtdate", models.DateTimeField()),
                ("monthly_avr", models.CharField(max_length=10)),
            ],
        ),
    ]
