# Generated by Django 4.2.1 on 2023-06-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regexpenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="cat",
            field=models.IntegerField(
                choices=[(0, "기본식비(외식등)"), (1, "유흥(놀고먹는거)"), (2, "기타")], default=0
            ),
        ),
    ]
